In [6]:
import pandas as pd
import numpy as np
list1 = pd.read_csv('./transaction-data/user-0.csv')

In [23]:
list1.head()
list1.dropna(axis=0, how='all')

,auth_id,Date,Vendor,Amount,Location
0,624,1/2/2013,Public Transportation - Train Pass,-23.89,CA
1,624,1/3/2013,Michael's Crafts,-23.22,CA
2,624,1/4/2013,Music Lessons - Piano,-17.40,CA
3,624,1/5/2013,Amazon Order - Paint Bushes,-21.16,CA
4,624,1/5/2013,Painting Course Fees,-65.86,CA
5,624,1/5/2013,Restaurant - Pizza,-75.29,CA
6,624,1/5/2013,Art Auction,-22.10,CA
7,624,1/6/2013,Amazon Order - Paint Canvas,-35.61,CA
8,624,1/6/2013,Lyft,-98.29,CA
9,624,1/7/2013,Guitar Center,-11.87,CA
10,624,1/7/2013,Art's Art Supplies,-117.99,CA
11,624,1/7/2013,Amazon Order - Paint Bushes,-19.26,CA
12,624,1/7/2013,Michael's Crafts,-28.50,CA
13,624,1/8/2013,Art Auction,-4.26,CA
14,624,1/8/2013,Public Transportation - Train Pass,-24.28,CA
15,624,1/8/2013,Art Auction,-18.06,CA
16,624,1/8/2013,Art Auction,-37.50,CA
17,624,1/8/2013,Ashley's Craft Store,-28.20,CA
18,624,1/9/2013,Art's Art Supplies,-21.72,CA
19,624,1/9/2013,Ralph's Grocery Store,-6.27,CA
20,624,1/10/2013,Restaurant - Burgers,-17.39,CA
21,624,1/10/2013,Art's Art Supplies,-7.89,CA
22,624,1/10/2013,Restaurant - Burgers,-71.87,CA
23,624,1/11/2013,Restaurant - Pizza,-104.02,CA
24,624,1/11/2013,Ashley's Craft Store,-25.67,CA
25,624,1/11/2013,Amazon Order - Paint Canvas,-0.01,CA
26,624,1/11/2013,Art's Art Supplies,-111.48,CA
27,624,1/11/2013,Art's Art Supplies,-39.65,CA
28,624,1/12/2013,Painting Course Fees,-108.50,CA
29,624,1/12/2013,Sprouts Market,-29.71,CA
...,...,...,...,...,...
2298,624,12/21/2014,Public Transportation - Train Pass,-5.53,CA
2299,624,12/22/2014,Painting Course Fees,-34.21,CA
2300,624,12/22/2014,Amazon Order - Paint Bushes,-16.82,CA
2301,624,12/22/2014,Ralph's Grocery Store,-32.41,CA
2302,624,12/22/2014,Music Lessons - Piano,-26.57,CA
2303,624,12/22/2014,Lyft,-8.76,CA
2304,624,12/22/2014,Lyft,-18.59,CA
2305,624,12/23/2014,Sprouts Market,-5.87,CA
2306,624,12/24/2014,Guitar Center,-15.66,CA
2307,624,12/24/2014,Music Lessons - Piano,-21.44,CA
2308,624,12/24/2014,Guitar Center,-33.36,CA
2309,624,12/25/2014,Food Delivery - GrubHub,-63.70,CA
2310,624,12/25/2014,Taxi,-99.89,CA
2311,624,12/26/2014,Starbucks Coffee,-23.19,CA
2312,624,12/27/2014,Amazon Order - Paint Bushes,-38.45,CA
2313,624,12/27/2014,Taxi,-24.90,CA
2314,624,12/27/2014,Public Transportation - Train Pass,-15.43,CA
2315,624,12/27/2014,Art Auction,-55.12,CA
2316,624,12/27/2014,Art's Art Supplies,-19.05,CA
2317,624,12/27/2014,Uber,-20.98,CA
2318,624,12/27/2014,Art's Art Supplies,-28.68,CA
2319,624,12/28/2014,Art's Art Supplies,-14.61,CA
2320,624,12/28/2014,Amazon Order - Paint Canvas,-31.28,CA
2321,624,12/28/2014,Guitar Center,-4.30,CA
2322,624,12/28/2014,Amazon Order - Paint Canvas,-32.00,CA
2323,624,12/28/2014,Art Auction,-12.77,CA
2324,624,12/28/2014,Art's Art Supplies,-7.23,CA
2325,624,12/29/2014,Whole Foods,-15.31,CA
2326,624,12/30/2014,Art Auction,-25.80,CA
2327,624,12/32/2014,Restaurant - Steakhouse,-8.30,CA

In [37]:
print list1.keys()

Index([u'auth_id', u' Date', u' Vendor', u' Amount', u' Location '], dtype='object')

We figure out that some keys have extra initial space

In [20]:
print(list1.keys())

Index([u'auth_id', u' Date', u' Vendor', u' Amount', u' Location '], dtype='object')

In [39]:
list1.columns=['auth_id','Date','Vendor', 'Amount','Location']

In [21]:
print list1

      auth_id        Date                              Vendor   Amount  \
0         624    1/2/2013  Public Transportation - Train Pass   -23.89
1         624    1/3/2013                    Michael's Crafts   -23.22
2         624    1/4/2013               Music Lessons - Piano   -17.40
3         624    1/5/2013         Amazon Order - Paint Bushes   -21.16
4         624    1/5/2013                Painting Course Fees   -65.86
5         624    1/5/2013                  Restaurant - Pizza   -75.29
6         624    1/5/2013                         Art Auction   -22.10
7         624    1/6/2013         Amazon Order - Paint Canvas   -35.61
8         624    1/6/2013                                Lyft   -98.29
9         624    1/7/2013                       Guitar Center   -11.87
10        624    1/7/2013                  Art's Art Supplies  -117.99
11        624    1/7/2013         Amazon Order - Paint Bushes   -19.26
12        624    1/7/2013                    Michael's Crafts   -28.50
13        624    1/8/2013                         Art Auction    -4.26
14        624    1/8/2013  Public Transportation - Train Pass   -24.28
15        624    1/8/2013                         Art Auction   -18.06
16        624    1/8/2013                         Art Auction   -37.50
17        624    1/8/2013                Ashley's Craft Store   -28.20
18        624    1/9/2013                  Art's Art Supplies   -21.72
19        624    1/9/2013               Ralph's Grocery Store    -6.27
20        624   1/10/2013                Restaurant - Burgers   -17.39
21        624   1/10/2013                  Art's Art Supplies    -7.89
22        624   1/10/2013                Restaurant - Burgers   -71.87
23        624   1/11/2013                  Restaurant - Pizza  -104.02
24        624   1/11/2013                Ashley's Craft Store   -25.67
25        624   1/11/2013         Amazon Order - Paint Canvas    -0.01
26        624   1/11/2013                  Art's Art Supplies  -111.48
27        624   1/11/2013                  Art's Art Supplies   -39.65
28        624   1/12/2013                Painting Course Fees  -108.50
29        624   1/12/2013                      Sprouts Market   -29.71
...       ...         ...                                 ...      ...
2298      624  12/21/2014  Public Transportation - Train Pass    -5.53
2299      624  12/22/2014                Painting Course Fees   -34.21
2300      624  12/22/2014         Amazon Order - Paint Bushes   -16.82
2301      624  12/22/2014               Ralph's Grocery Store   -32.41
2302      624  12/22/2014               Music Lessons - Piano   -26.57
2303      624  12/22/2014                                Lyft    -8.76
2304      624  12/22/2014                                Lyft   -18.59
2305      624  12/23/2014                      Sprouts Market    -5.87
2306      624  12/24/2014                       Guitar Center   -15.66
2307      624  12/24/2014               Music Lessons - Piano   -21.44
2308      624  12/24/2014                       Guitar Center   -33.36
2309      624  12/25/2014             Food Delivery - GrubHub   -63.70
2310      624  12/25/2014                                Taxi   -99.89
2311      624  12/26/2014                    Starbucks Coffee   -23.19
2312      624  12/27/2014         Amazon Order - Paint Bushes   -38.45
2313      624  12/27/2014                                Taxi   -24.90
2314      624  12/27/2014  Public Transportation - Train Pass   -15.43
2315      624  12/27/2014                         Art Auction   -55.12
2316      624  12/27/2014                  Art's Art Supplies   -19.05
2317      624  12/27/2014                                Uber   -20.98
2318      624  12/27/2014                  Art's Art Supplies   -28.68
2319      624  12/28/2014                  Art's Art Supplies   -14.61
2320      624  12/28/2014         Amazon Order - Paint Canvas   -31.28
2321      624  12/28/2014                       Guitar Center    -4.30
2322      624  12/28/2014         Amazon Order - Paint Canvas   -32.00
2323      624  12/28/2014                         Art Auction   -12.77
2324      624  12/28/2014                  Art's Art Supplies    -7.23
2325      624  12/29/2014                         Whole Foods   -15.31
2326      624  12/30/2014                         Art Auction   -25.80
2327      624  12/32/2014             Restaurant - Steakhouse    -8.30

      Location
0            CA
1            CA
2            CA
3            CA
4            CA
5            CA
6            CA
7            CA
8            CA
9            CA
10           CA
11           CA
12           CA
13           CA
14           CA
15           CA
16           CA
17           CA
18           CA
19           CA
20           CA
21           CA
22           CA
23           CA
24           CA
25           CA
26           CA
27           CA
28           CA
29           CA
...         ...
2298         CA
2299         CA
2300         CA
2301         CA
2302         CA
2303         CA
2304         CA
2305         CA
2306         CA
2307         CA
2308         CA
2309         CA
2310         CA
2311         CA
2312         CA
2313         CA
2314         CA
2315         CA
2316         CA
2317         CA
2318         CA
2319         CA
2320         CA
2321         CA
2322         CA
2323         CA
2324         CA
2325         CA
2326         CA
2327         CA

[2328 rows x 5 columns]

In [42]:
Total = list1['Amount'].mean()
print (Total)

-19.4924269759

In [45]:
list1[['Date','Amount']].groupby(['Date']).sum()

           Amount
Date
1/10/2013  -97.15
1/10/2014 -146.33
1/11/2013 -280.83
1/11/2014 -115.36
1/12/2013 -174.58
1/12/2014 -115.87
1/13/2013   -8.64
1/13/2014  -61.95
1/14/2013 -103.18
1/14/2014 -166.13
1/15/2013   -2.28
1/15/2014 -223.56
1/16/2013 -196.69
1/16/2014   -8.94
1/17/2013 -141.41
1/17/2014  -59.01
1/18/2013  -63.26
1/18/2014  -28.67
1/19/2013 -416.01
1/19/2014  -21.16
1/2/2013   -23.89
1/2/2014   -88.59
1/20/2013  -20.10
1/20/2014   -3.18
1/21/2013  -52.25
1/21/2014 -115.52
1/22/2013 -155.43
1/22/2014 -119.52
1/23/2013  -99.28
1/23/2014  -23.56
...           ...
9/23/2013 -182.51
9/23/2014  -78.00
9/24/2013 -259.25
9/24/2014  -53.29
9/25/2013  -33.28
9/25/2014  -70.57
9/26/2013  -46.88
9/26/2014 -102.40
9/27/2013   -4.99
9/27/2014   -7.93
9/28/2013 -170.14
9/28/2014  -36.87
9/29/2013  -40.81
9/29/2014  -27.46
9/3/2013  -186.98
9/3/2014   -35.31
9/30/2013  -16.84
9/30/2014   -4.10
9/4/2013   -10.96
9/4/2014   -98.43
9/5/2013  -199.88
9/5/2014  -114.34
9/6/2013  -154.37
9/6/2014  -105.86
9/7/2013   -26.91
9/7/2014   -56.56
9/8/2013  -231.21
9/8/2014    -3.71
9/9/2013   -49.94
9/9/2014   -33.57

[640 rows x 1 columns]

In [46]:
list1[['Date','Amount']].groupby(['Date']).count()

           Amount
Date
1/10/2013       3
1/10/2014       5
1/11/2013       5
1/11/2014       4
1/12/2013       4
1/12/2014       5
1/13/2013       1
1/13/2014       3
1/14/2013       1
1/14/2014       7
1/15/2013       1
1/15/2014       3
1/16/2013       6
1/16/2014       1
1/17/2013       6
1/17/2014       2
1/18/2013       2
1/18/2014       2
1/19/2013      11
1/19/2014       1
1/2/2013        1
1/2/2014        2
1/20/2013       1
1/20/2014       1
1/21/2013       1
1/21/2014       5
1/22/2013       4
1/22/2014       6
1/23/2013       1
1/23/2014       1
...           ...
9/23/2013       6
9/23/2014       3
9/24/2013       3
9/24/2014       2
9/25/2013       2
9/25/2014       5
9/26/2013       3
9/26/2014       2
9/27/2013       1
9/27/2014       1
9/28/2013       7
9/28/2014       3
9/29/2013       2
9/29/2014       1
9/3/2013        3
9/3/2014        2
9/30/2013       1
9/30/2014       1
9/4/2013        1
9/4/2014        2
9/5/2013        5
9/5/2014        1
9/6/2013        5
9/6/2014        4
9/7/2013        4
9/7/2014        3
9/8/2013        6
9/8/2014        1
9/9/2013        1
9/9/2014        1

[640 rows x 1 columns]

In [53]:
len(list1['Location'].value_counts())

1

In [52]:
len(list1['Date'].value_counts())

640

In [54]:
len(list1['auth_id'].value_counts())

1